### ISSUE TITLE
Syntax error in interpreter.json

### ISSUE THREAD

**Issue by pergus** [cuebook/cuelake#7]
There is a syntax error (missing comma) on line 1275 in  https://raw.githubusercontent.com/cuebook/cuelake/main/zeppelinConf/interpreter.json

Also, there is a \t on lines 1271 and 1272 that I suspect are incorrect.

And finally if you use less to view the content it C in the word Comma on line 201 is displayed as <D0><A1>.

Below is a diff file or the changes that I made to the file.
```
201c201
<           "description": "Сomma separated schema (schema \u003d catalog \u003d database) filters to get metadata for completions. Supports \u0027%\u0027 symbol is equivalent to any set of characters. (ex. prod_v_%,public%,info)"
---
>           "description": "Comma separated schema (schema \u003d catalog \u003d database) filters to get metadata for completions. Supports \u0027%\u0027 symbol is equivalent to any set of characters. (ex. prod_v_%,public%,info)"
1271,1272c1271,1272
<         "spark.executor.extraJavaOptions\t": {
<           "name": "spark.executor.extraJavaOptions\t",
---
>         "spark.executor.extraJavaOptions": {
>           "name": "spark.executor.extraJavaOptions",
1275c1275
<         }
---
>         },
```

**Comment by Prabhu31** [comment]
Fixed the syntax error in json file. **\t**s are fine, when read by zeppelin they are ignored, but will clean the file in future and also add more documentation around the configuration.
